version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mini_rag_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mini_rag_network

  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: mini_rag_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./src/assets/db/qdrant_data:/qdrant/storage
    networks:
      - mini_rag_network

volumes:
  mongodb_data:

networks:
  mini_rag_network:
    driver: bridge